
services:
  user-service:
    image: ${DOCKER_REGISTRY:-ghcr.io/sentiric}/sentiric-user-service:${TAG:-latest}
    build: { context: . }
    container_name: sentiric_user_service
    env_file: [./.env]
    networks: [sentiric-net]
    restart: unless-stopped
networks:
  sentiric-net:
    name: ${NETWORK_NAME:-sentiric-net}
    driver: bridge