services:
  user-service:
    image: ${DOCKER_REGISTRY:-ghcr.io/sentiric}/sentiric-user-service:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sentiric_user_service
    env_file:
      - ./.env
    # YENİ EKLENEN BÖLÜM:
    environment:
      - GRPC_PORT=${INTERNAL_GRPC_PORT_USER}
      - DATABASE_URL=${POSTGRES_URL}
    # user-service'in, postgres servisi sağlıklı bir şekilde çalışmaya başlamadan
    # başlamamasını sağlıyoruz. Bu çok önemli.
    # depends_on:
    #   postgres:
    #     condition: service_healthy
    networks:
      - sentiric-net
    restart: always

networks:
  sentiric-net:
    name: ${NETWORK_NAME:-sentiric-net}
    driver: bridge