networks:
  sentiric-net:
    name: ${NETWORK_NAME:-sentiric-net}
    driver: bridge

volumes:
  postgres_data:

services:
  # VERİ KATMANI
  postgres:
    image: postgres:16-alpine
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../sentiric-config/postgres-init:/docker-entrypoint-initdb.d
    # ports:
    #   - "${POSTGRES_DB_PORT}:${POSTGRES_DB_PORT}"
    networks:
      - sentiric-net
    profiles:
      - default
      - data
    restart: always

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5    

  # UYGULAMA SERVİSLERİ
  user-service:

    build:
      context: .
      dockerfile: Dockerfile         
      args:
        SERVICE_NAME: sentiric-user-service

    env_file: 
      - ./.env

    volumes:
      - ../sentiric-config/tls/certs:/etc/sentiric/tls:ro
      
    # ports:
    #   - "${USER_SERVICE_GRPC_PORT}:${USER_SERVICE_GRPC_PORT}"

    networks:
      - sentiric-net

    profiles:
      - default
      - app

    restart: always

    depends_on:
      postgres:
        condition: service_healthy    